spring:
  profiles:
    active: local # default
    # 여러 프로파일을 한번에 실행시킬 때 Group 사용
    group:
      local:
        - common
      prod:
        - common
---
spring:
  config:
    activate:
      on-profile: common

# ...
---
# Local 환경
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pharmacy-recommendation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql

---
# cloud 환경
spring:
  config:
    activate:
      on-profile: prod